/**
 * PokéAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInner } from './apiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInner';
import { ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerVersion } from './apiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerVersion';


export interface ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner { 
    encounter_details: Array<ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerEncounterDetailsInner>;
    max_chance: number;
    version: ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInnerVersion;
}

