/**
 * PokéAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV2PokemonEncountersRetrieve200ResponseInnerLocationArea } from './apiV2PokemonEncountersRetrieve200ResponseInnerLocationArea';
import { ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner } from './apiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner';


export interface ApiV2PokemonEncountersRetrieve200ResponseInner { 
    location_area: ApiV2PokemonEncountersRetrieve200ResponseInnerLocationArea;
    version_details: Array<ApiV2PokemonEncountersRetrieve200ResponseInnerVersionDetailsInner>;
}

