/**
 * PokéAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AbilityDetailPokemonInnerPokemon } from './abilityDetailPokemonInnerPokemon';
import { ItemDetailHeldByPokemonInnerVersionDetailsInner } from './itemDetailHeldByPokemonInnerVersionDetailsInner';


export interface PokemonDetailHeldItemsInner { 
    item: AbilityDetailPokemonInnerPokemon;
    version_details: Array<ItemDetailHeldByPokemonInnerVersionDetailsInner>;
}

